auth:
    type: "allowall"

cache:
    type: "redis"
    host: "$DINO_REDIS_HOST"
    db: $DINO_REDIS_DB

db:
    uri: "$DINO_DB_URI"

storage:
    host: "$DINO_STORAGE_HOSTS"
    key_space: "$DINO_STORAGE_KEY_SPACE"

coordinator:
    host: "$DINO_COORDINATOR_HOST"
    db: $DINO_COORDINATOR_DB

stats:
    type: "mock"

kafka:
    topic: "$DINO_KAFKA_TOPIC"
    host: "$DINO_KAFKA_HOSTS"
