auth:
    type: "allowall"

cache:
    type: "memory"

db:
    uri: "$DINO_DB_URI"

storage:
    host: "$DINO_STORAGE_HOSTS"
    key_space: "$DINO_STORAGE_KEY_SPACE"

coordinator:
    host: "$DINO_COORDINATOR_HOST"
    db: $DINO_COORDINATOR_DB

stats:
    type: "mock"
